# Generated by Django 3.2.13 on 2022-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220426_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
