# Generated by Django 3.2.13 on 2022-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_shippingaddress_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
