# Generated by Django 3.2.13 on 2022-04-27 09:13

from django.db import migrations, models
import eshopper.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=eshopper.main.models.default_random_transaction_id, max_length=100, null=True),
        ),
    ]
