# Generated by Django 3.2.13 on 2022-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('dresses', 'dresses'), ('jeans', 'jeans'), ('jackets', 'jackets'), ('T-shirts', 'T-shirts'), ('shoes', 'shoes')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
