# Generated by Django 3.2.13 on 2022-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('dresses', 'dresses'), ('jeans', 'jeans'), ('jackets', 'jackets'), ('T-shirts', 'T-shirts')], max_length=100),
        ),
    ]
